// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using travelapp.Data;

#nullable disable

namespace travelapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("travelapp.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 34,
                            CityUrl = "/Pictures/kizkulesi.png",
                            Name = "İstanbul"
                        },
                        new
                        {
                            CityId = 6,
                            CityUrl = "/Pictures/anitkabir.png",
                            Name = "Ankara"
                        },
                        new
                        {
                            CityId = 35,
                            CityUrl = "/Pictures/saatkulesi.png",
                            Name = "İzmir"
                        },
                        new
                        {
                            CityId = 26,
                            CityUrl = "/Pictures/eskisehir.png",
                            Name = "Eskişehir"
                        },
                        new
                        {
                            CityId = 17,
                            CityUrl = "/Pictures/canakkale.png",
                            Name = "Çanakkale"
                        });
                });

            modelBuilder.Entity("travelapp.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Comment = "İdare eder.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2691),
                            PlaceId = 1,
                            Rating = 3,
                            UserName = "Ziyaretçi 1"
                        },
                        new
                        {
                            FeedbackId = 2,
                            Comment = "Çok fazla kalabalık vardı.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2694),
                            PlaceId = 1,
                            Rating = 2,
                            UserName = "Ziyaretçi 2"
                        },
                        new
                        {
                            FeedbackId = 3,
                            Comment = "Etkileyici.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2696),
                            PlaceId = 3,
                            Rating = 4,
                            UserName = "Ziyaretçi 3"
                        },
                        new
                        {
                            FeedbackId = 4,
                            Comment = "Görülmeli.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2697),
                            PlaceId = 4,
                            Rating = 4,
                            UserName = "Ziyaretçi 4"
                        },
                        new
                        {
                            FeedbackId = 5,
                            Comment = "Hissiyatı çok yüksek.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2698),
                            PlaceId = 5,
                            Rating = 5,
                            UserName = "Vatandaş"
                        },
                        new
                        {
                            FeedbackId = 6,
                            Comment = "Herkesin gitmesi gereken bir yer.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2699),
                            PlaceId = 5,
                            Rating = 5,
                            UserName = "Ahmet"
                        },
                        new
                        {
                            FeedbackId = 7,
                            Comment = "Her şey çok gerçekçi.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2733),
                            PlaceId = 6,
                            Rating = 4,
                            UserName = "Mehmet"
                        },
                        new
                        {
                            FeedbackId = 8,
                            Comment = "Güzel.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2734),
                            PlaceId = 8,
                            Rating = 4,
                            UserName = "Ayşe"
                        },
                        new
                        {
                            FeedbackId = 9,
                            Comment = "Muazzam tarih.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2735),
                            PlaceId = 10,
                            Rating = 5,
                            UserName = "Turist"
                        },
                        new
                        {
                            FeedbackId = 10,
                            Comment = "Çok fazla sıra bekleniyor.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2736),
                            PlaceId = 11,
                            Rating = 2,
                            UserName = "Fatma"
                        },
                        new
                        {
                            FeedbackId = 11,
                            Comment = "Çocuklar için iyi.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2738),
                            PlaceId = 12,
                            Rating = 3,
                            UserName = "Veli"
                        },
                        new
                        {
                            FeedbackId = 12,
                            Comment = "Çok güzel!",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2739),
                            PlaceId = 13,
                            Rating = 5,
                            UserName = "Gezgin"
                        },
                        new
                        {
                            FeedbackId = 13,
                            Comment = "Tarihi dokusu harika.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2740),
                            PlaceId = 13,
                            Rating = 4,
                            UserName = "Tarihçi"
                        },
                        new
                        {
                            FeedbackId = 14,
                            Comment = "Çok fazla sıra bekledik.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2741),
                            PlaceId = 14,
                            Rating = 2,
                            UserName = "Ziyaretçi"
                        },
                        new
                        {
                            FeedbackId = 15,
                            Comment = "Romantik bir yürüyüş için ideal.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2743),
                            PlaceId = 15,
                            Rating = 5,
                            UserName = "Aşıklar"
                        },
                        new
                        {
                            FeedbackId = 16,
                            Comment = "Duygusal.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2744),
                            PlaceId = 16,
                            Rating = 5,
                            UserName = "Mehmetçik"
                        },
                        new
                        {
                            FeedbackId = 17,
                            Comment = "Bakımlı.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2745),
                            PlaceId = 16,
                            Rating = 4,
                            UserName = "Ziyaretçi"
                        },
                        new
                        {
                            FeedbackId = 18,
                            Comment = "Geliştirilmeli.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2746),
                            PlaceId = 17,
                            Rating = 2,
                            UserName = "Eleştirmen"
                        },
                        new
                        {
                            FeedbackId = 19,
                            Comment = "Beklentinin altında bir yer.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2747),
                            PlaceId = 17,
                            Rating = 3,
                            UserName = "Ziyaretçi"
                        },
                        new
                        {
                            FeedbackId = 20,
                            Comment = "Yol biraz zorlu.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2749),
                            PlaceId = 18,
                            Rating = 3,
                            UserName = "Şoför"
                        },
                        new
                        {
                            FeedbackId = 21,
                            Comment = "Manzara güzel.",
                            Date = new DateTime(2025, 12, 11, 11, 26, 3, 827, DateTimeKind.Local).AddTicks(2750),
                            PlaceId = 18,
                            Rating = 4,
                            UserName = "Fotoğrafçı"
                        });
                });

            modelBuilder.Entity("travelapp.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaceId");

                    b.HasIndex("CityId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            CityId = 34,
                            Description = "Şehrin harika manzarası.",
                            ImageUrl = "/Pictures/galata.png",
                            Name = "Galata Kulesi"
                        },
                        new
                        {
                            PlaceId = 2,
                            CityId = 34,
                            Description = "Boğazın incisi.",
                            ImageUrl = "/Pictures/kizkulesi.png",
                            Name = "Kız Kulesi"
                        },
                        new
                        {
                            PlaceId = 3,
                            CityId = 34,
                            Description = "Tarihi yarımadanın kalbi.",
                            ImageUrl = "/Pictures/sultanahmet.png",
                            Name = "Sultan Ahmet Cami"
                        },
                        new
                        {
                            PlaceId = 4,
                            CityId = 34,
                            Description = "Gizemli sarnıç.",
                            ImageUrl = "/Pictures/yerebatan.png",
                            Name = "Yerebatan Sarnıcı"
                        },
                        new
                        {
                            PlaceId = 5,
                            CityId = 6,
                            Description = "Atamızın istirahatgahı.",
                            ImageUrl = "/Pictures/anitkabir.png",
                            Name = "Anıtkabir"
                        },
                        new
                        {
                            PlaceId = 6,
                            CityId = 6,
                            Description = "Tarihi cezaevi müzesi.",
                            ImageUrl = "/Pictures/ulucanlar.png",
                            Name = "Ulucanlar Cezaevi"
                        },
                        new
                        {
                            PlaceId = 7,
                            CityId = 6,
                            Description = "Huzurlu bir park.",
                            ImageUrl = "/Pictures/kugulupark.png",
                            Name = "Kuğulu Park"
                        },
                        new
                        {
                            PlaceId = 8,
                            CityId = 6,
                            Description = "Meclis tarihi.",
                            ImageUrl = "/Pictures/tbmm.png",
                            Name = "TBMM Müzesi"
                        },
                        new
                        {
                            PlaceId = 9,
                            CityId = 35,
                            Description = "İzmir'in sembolü.",
                            ImageUrl = "/Pictures/saatkulesi.png",
                            Name = "Saat Kulesi"
                        },
                        new
                        {
                            PlaceId = 10,
                            CityId = 35,
                            Description = "Antik tarih.",
                            ImageUrl = "/Pictures/efes.png",
                            Name = "Efes Antik Kenti"
                        },
                        new
                        {
                            PlaceId = 11,
                            CityId = 35,
                            Description = "Manzara noktası.",
                            ImageUrl = "/Pictures/tarihiasansor.png",
                            Name = "Tarihi Asansör"
                        },
                        new
                        {
                            PlaceId = 12,
                            CityId = 26,
                            Description = "Masalsı bir yapı.",
                            ImageUrl = "/Pictures/eskisehir.png",
                            Name = "Masal Şatosu"
                        },
                        new
                        {
                            PlaceId = 13,
                            CityId = 26,
                            Description = "Renkli tarihi evler.",
                            ImageUrl = "/Pictures/odunpazari.png",
                            Name = "Odunpazarı Evleri"
                        },
                        new
                        {
                            PlaceId = 14,
                            CityId = 26,
                            Description = "Ünlülerin heykelleri.",
                            ImageUrl = "/Pictures/balmumu.png",
                            Name = "Balmumu Müzesi"
                        },
                        new
                        {
                            PlaceId = 15,
                            CityId = 26,
                            Description = "Gondol keyfi.",
                            ImageUrl = "/Pictures/porsuk.png",
                            Name = "Porsuk Çayı"
                        },
                        new
                        {
                            PlaceId = 16,
                            CityId = 17,
                            Description = "Saygı duruşu.",
                            ImageUrl = "/Pictures/eskisehir.png",
                            Name = "Şehitler Abidesi"
                        },
                        new
                        {
                            PlaceId = 17,
                            CityId = 17,
                            Description = "Denizcilik tarihi.",
                            ImageUrl = "/Pictures/denizmuzesi.png",
                            Name = "Deniz Müzesi"
                        },
                        new
                        {
                            PlaceId = 18,
                            CityId = 17,
                            Description = "Antik felsefe kenti.",
                            ImageUrl = "/Pictures/assos.png",
                            Name = "Assos Antik Kenti"
                        },
                        new
                        {
                            PlaceId = 19,
                            CityId = 17,
                            Description = "Efsanevi savaş kenti.",
                            ImageUrl = "/Pictures/truva.png",
                            Name = "Truva Antik Kenti"
                        });
                });

            modelBuilder.Entity("travelapp.Models.Feedback", b =>
                {
                    b.HasOne("travelapp.Models.Place", "Place")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("travelapp.Models.Place", b =>
                {
                    b.HasOne("travelapp.Models.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("travelapp.Models.City", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("travelapp.Models.Place", b =>
                {
                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
